// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZNBMQbQhIdB2HN04HPUNV5OiNYbz1fG4',
    appId: '1:913741131867:web:d5eef0652fea120eb4cf7e',
    messagingSenderId: '913741131867',
    projectId: 'fountain-finder-3306a',
    authDomain: 'fountain-finder-3306a.firebaseapp.com',
    storageBucket: 'fountain-finder-3306a.firebasestorage.app',
    measurementId: 'G-179Y0FN2JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPvacJtngf8AYRyHEYC04Fl9iqGtXL3_4',
    appId: '1:913741131867:android:92de64cca3d5513db4cf7e',
    messagingSenderId: '913741131867',
    projectId: 'fountain-finder-3306a',
    storageBucket: 'fountain-finder-3306a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgGuDneDOJxsrWCWOpI6XH0TsEMIU0mYs',
    appId: '1:913741131867:ios:cb032d33f976da77b4cf7e',
    messagingSenderId: '913741131867',
    projectId: 'fountain-finder-3306a',
    storageBucket: 'fountain-finder-3306a.firebasestorage.app',
    iosBundleId: 'com.example.fountainFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgGuDneDOJxsrWCWOpI6XH0TsEMIU0mYs',
    appId: '1:913741131867:ios:cb032d33f976da77b4cf7e',
    messagingSenderId: '913741131867',
    projectId: 'fountain-finder-3306a',
    storageBucket: 'fountain-finder-3306a.firebasestorage.app',
    iosBundleId: 'com.example.fountainFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZNBMQbQhIdB2HN04HPUNV5OiNYbz1fG4',
    appId: '1:913741131867:web:a405a1b97ceb4ed7b4cf7e',
    messagingSenderId: '913741131867',
    projectId: 'fountain-finder-3306a',
    authDomain: 'fountain-finder-3306a.firebaseapp.com',
    storageBucket: 'fountain-finder-3306a.firebasestorage.app',
    measurementId: 'G-F8WCJ9YSRV',
  );
}
